apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: mongodb
    spec:
      containers:
      - image: mongo:4.4.6
        name: mongodb
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-volume
            mountPath: /data/db
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-v-claim
