apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mongodb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/data/mongodb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongodb-v-claim
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce 
  resources:
    requests:
      storage: 20Gi
