apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP # Exposes the Service on a cluster-internal IP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector: 
    app: mongodb 