apiVersion: v1
kind: Service
metadata:
  name: websocket
spec:
  type: LoadBalancer # Exposes the Service on a cluster-internal IP
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  selector: 
    app: websocket 