apiVersion: v1
kind: PersistentVolume
metadata: 
  name: keycloak-db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/data/keycloak-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: keycloak-db-v-claim
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce 
  resources:
    requests:
      storage: 20Gi


# kubectl get pvc

# kubectl apply -f keycloak-db/persisten-volume.yml



# kubectl delete pvc keycloak-db-v-claim
# kubectl delete pv keycloak-db-volume