apiVersion: v1
data:
  db_name: a2V5Y2xvYWs=
  user: a2V5Y2xvYWs=
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret

# kubectl apply -f keycloak-db/secret.yml