apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  type: ClusterIP # Exposes the Service on a cluster-internal IP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector: 
    app: keycloak-db 