// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace DataHandlerSQL.Model
{
    public partial class DocAnalyzerContext : DbContext
    {
        public DocAnalyzerContext()
        {
        }

        public DocAnalyzerContext(DbContextOptions<DocAnalyzerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeReferenceByDocument> EmployeeReferenceByDocument { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Spanish_Costa Rica.1252");

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.ToTable("employee");

                entity.Property(e => e.EmployeeId).HasColumnName("employee_id");

                entity.Property(e => e.FullName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("full_name");
            });

            modelBuilder.Entity<EmployeeReferenceByDocument>(entity =>
            {
                entity.HasKey(e => new { e.EmployeeId, e.DocumentId })
                    .HasName("employee_reference_by_document_pkey");

                entity.ToTable("employee_reference_by_document");

                entity.Property(e => e.EmployeeId).HasColumnName("employee_id");

                entity.Property(e => e.DocumentId)
                    .HasMaxLength(50)
                    .HasColumnName("document_id");

                entity.Property(e => e.Ocurrences)
                    .HasColumnName("ocurrences")
                    .HasDefaultValueSql("0");

                entity.HasOne(d => d.Employee)
                    .WithMany(p => p.EmployeeReferenceByDocument)
                    .HasForeignKey(d => d.EmployeeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_employee_id");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}