// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataHandlerSQL.Model
{
    [Table("employee")]
    public partial class Employee
    {
        public Employee()
        {
            EmployeeReferenceByDocument = new HashSet<EmployeeReferenceByDocument>();
        }

        [Key]
        [Column("employee_id")]
        public int EmployeeId { get; set; }
        [Required]
        [Column("full_name")]
        [StringLength(100)]
        public string FullName { get; set; }

        [InverseProperty("Employee")]
        public virtual ICollection<EmployeeReferenceByDocument> EmployeeReferenceByDocument { get; set; }
    }
}