// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataHandlerSQL.Model
{
    public partial class EmployeeReferenceByDocument
    {
        public int EmployeeId { get; set; }
        public string DocumentId { get; set; }
        public int? Ocurrences { get; set; }

        public virtual Employee Employee { get; set; }
    }
}