// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataHandlerSQL.Model
{
    [Table("employee_reference_by_document")]
    public partial class EmployeeReferenceByDocument
    {
        [Key]
        [Column("employee_id")]
        public int EmployeeId { get; set; }
        [Key]
        [Column("document_id")]
        [StringLength(50)]
        public string DocumentId { get; set; }
        [Column("ocurrences")]
        public int? Ocurrences { get; set; }

        [ForeignKey(nameof(EmployeeId))]
        [InverseProperty("EmployeeReferenceByDocument")]
        public virtual Employee Employee { get; set; }
    }
}