// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataHandlerSQL.Model
{
    public partial class Employee
    {
        public Employee()
        {
            EmployeeReferenceByDocument = new HashSet<EmployeeReferenceByDocument>();
        }

        public int EmployeeId { get; set; }
        public string FullName { get; set; }

        public virtual ICollection<EmployeeReferenceByDocument> EmployeeReferenceByDocument { get; set; }
    }
}