// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace DataHandlerSQL.Model
{
    [Table("user_credential")]
    [IndexAttribute(nameof(Email), Name = "user_credential_email_key", IsUnique = true)]
    public partial class UserCredential
    {
        [Key]
        [Column("user_id")]
        public int UserId { get; set; }
        [Required]
        [Column("full_name")]
        [StringLength(100)]
        public string FullName { get; set; }
        [Required]
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        [Required]
        [Column("user_password")]
        [StringLength(100)]
        public string UserPassword { get; set; }
    }
}