apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
data:
  connection_url: YW1xcHM6Ly9heWZwd2JleDpNX2NNRWhQLXpFMVZLU2R1eVphMDJiY2NrMDd6QzgtZEBvcmFuZ3V0YW4ucm1xLmNsb3VkYW1xcC5jb20vYXlmcHdiZXg=
