---
# Definition of Keycloak service
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service      # Name of endpoint object
spec:
  type: LoadBalancer
  selector:
    app: keycloak     # Matches any pod labeled keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


# kubectl apply -f keycloak-service.yml