version: '3'

volumes:
  # MongoDB persistent volume  
  docanalyzer-mongodb:
    driver: local
    name: docanalyzer-mongodb

  # PostgreSLQ persistent volume  
  docanalyzer-postgres:
    driver: local
    name: docanalyzer-postgres
    
services:
  # PostgreSQL Database
  postgres: 
    image: postgres
    volumes: 
      - docanalyzer-postgres:/var/lib/postgresql/data
      - ./postgres-config:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: 
        - 5051:5432
    
  # MongoDB Database
  mongodb:
    image: mongo:4.4.6
    volumes:
      - docanalyzer-mongodb:/data/db
    ports:
      - 3032:27017

# docker-compose -f docanalyzer.yml up
# docker-compose -f docanalyzer.yml down