# docker-compose -f keycloak-postgres.yml up

version: '3'

# Volume definition
volumes:
    keycloak-postgres-db:
        driver: local
        name: keycloak-postgres-db

# Configuration files
configs: 
    keycloak-realm-config:
        file: ./realm-export.json


services:
  # Keycloak Database
  postgres:
      image: postgres
      volumes:
        - keycloak-postgres-db:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports: 
        - 5050:5432
  
  # Keycloak Service  
  keycloak:
      image: jboss/keycloak:13.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres