apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentanalyzerapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documentanalyzerapi
  template:
    metadata:
      labels:
        app: documentanalyzerapi
    spec:
      containers:
        - name: documentanalyzerapi
          image: arturocv/documentanalyzerapi:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
            - name: KEYCLOAK_HOST
              value: keycloak-service
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: KEYCLOAK_REALMNAME
              value: docanalyzer
            - name: KEYCLOAK_TOKEN_AUTHTYPE
              value: Bearer

            - name: POSTGRES_HOST
              value: docanalyzer-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB_NAME
              value: docanalyzer
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: docanalyzer-postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docanalyzer-postgres-secret
                  key: password
            
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_NAME
              value: DocAnalyzer
