apiVersion: v1
kind: PersistentVolume
metadata: 
  name: docanalyzer-postgres-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/data/docanalyzer-postgres"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: docanalyzer-postgres-v-claim
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce 
  resources:
    requests:
      storage: 20Gi
