apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: docanalyzer-postgres-secret
data:
  db_name: cG9zdGdyZXM=
  user: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=

# kubectl apply -f keycloak-db/secret.yml