apiVersion: v1
kind: Service
metadata:
  name: docanalyzer-postgres
spec:
  type: NodePort # Exposes the Service on a cluster-internal IP
  ports:
    - protocol: TCP
      port: 5430
      targetPort: 5432
  selector: 
    app: docanalyzer-postgres